import { Product } from './types';

export const PRODUCTS: Product[] = [
  // --- FLAGSHIPS ---
  {
    id: 'iphone-17',
    name: 'iPhone 17',
    brand: 'Apple',
    category: 'Smartphone',
    price: 89900,
    condition: 'New',
    // Front View as main image
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=800&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=800&auto=format&fit=crop', // Front View (Titanium Grey)
      'https://images.unsplash.com/photo-1696446700403-2b2bf7061d44?q=80&w=800&auto=format&fit=crop', // Vertical Camera Detail
      'https://images.unsplash.com/photo-1696446701796-da61225697cc?q=80&w=800&auto=format&fit=crop', // Side Profile
      'https://images.unsplash.com/photo-1605236453806-6ff36a86fa2e?q=80&w=800&auto=format&fit=crop'  // What's in the Box
    ],
    specs: { storage: '128GB', ram: '8GB', color: 'Titanium Grey', screen: '6.1"' },
    description: 'Experience the future with iPhone 17. Featuring the all-new vertical camera system designed for Spatial Video, a refined titanium finish, and the powerful A18 chip. Inside the box: iPhone 17 and USB-C Charge Cable.',
    rating: 5.0,
    reviews: 1,
    isTrending: true,
  },
  {
    id: 's24-ultra',
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'Smartphone',
    price: 129999,
    originalPrice: 144999,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1610945415295-d96bf067d9e4?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '256GB', ram: '12GB', color: 'Titanium Gray', screen: '6.8"' },
    description: 'Galaxy AI is here. The ultimate productivity device with S-Pen integration and a massive 200MP camera.',
    rating: 4.9,
    reviews: 124,
    isTrending: true,
  },
  {
    id: 'pixel-8-pro',
    name: 'Google Pixel 8 Pro',
    brand: 'Google',
    category: 'Smartphone',
    price: 106999,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1698669527633-5c74384a6003?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '128GB', ram: '12GB', color: 'Bay Blue', screen: '6.7"' },
    description: 'The AI-first phone. Best-in-class camera with Magic Eraser and Night Sight.',
    rating: 4.8,
    reviews: 89,
    isTrending: true,
  },
  {
    id: 'oneplus-12',
    name: 'OnePlus 12',
    brand: 'OnePlus',
    category: 'Smartphone',
    price: 64999,
    originalPrice: 69999,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1678911820864-e2c567c655d7?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '256GB', ram: '12GB', color: 'Flowy Emerald', screen: '6.82"' },
    description: 'Smooth beyond belief. Snapdragon 8 Gen 3 with the brightest display ever on a OnePlus.',
    rating: 4.7,
    reviews: 210,
    isTrending: true,
  },
  {
    id: 'z-fold-5',
    name: 'Samsung Galaxy Z Fold 5',
    brand: 'Samsung',
    category: 'Smartphone',
    price: 154999,
    originalPrice: 184999,
    condition: 'Like New',
    image: 'https://images.unsplash.com/photo-1658428251010-0255855f750d?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '512GB', ram: '12GB', color: 'Icy Blue', screen: '7.6"' },
    description: 'PC-like power in your pocket. The ultimate foldable experience.',
    rating: 4.6,
    reviews: 45,
  },
  
  // --- APPLE COLLECTION ---
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    brand: 'Apple',
    category: 'Smartphone',
    price: 134900,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1696446700403-2b2bf7061d44?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '128GB', ram: '8GB', color: 'Black Titanium', screen: '6.1"' },
    description: 'Aerospace-grade titanium design. A17 Pro chip. The most powerful iPhone ever.',
    rating: 4.9,
    reviews: 320,
  },
  {
    id: 'iphone-14-plus',
    name: 'iPhone 14 Plus',
    brand: 'Apple',
    category: 'Smartphone',
    price: 65999,
    originalPrice: 79900,
    condition: 'Good',
    image: 'https://images.unsplash.com/photo-1663499482523-1c0c167b2d72?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '128GB', ram: '6GB', color: 'Purple', screen: '6.7"' },
    description: 'Big screen. Big battery life. A powerful dual-camera system.',
    rating: 4.5,
    reviews: 150,
  },
  {
    id: 'iphone-13-mini',
    name: 'iPhone 13 Mini',
    brand: 'Apple',
    category: 'Smartphone',
    price: 42999,
    condition: 'Like New',
    image: 'https://images.unsplash.com/photo-1632661674596-df8be070a5c5?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '128GB', ram: '4GB', color: 'Starlight', screen: '5.4"' },
    description: 'The compact superpower. Fits perfectly in your hand.',
    rating: 4.8,
    reviews: 88,
  },
  
  // --- SAMSUNG MID-RANGE & FLIP ---
  {
    id: 'z-flip-5',
    name: 'Samsung Galaxy Z Flip 5',
    brand: 'Samsung',
    category: 'Smartphone',
    price: 89999,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1627906936647-3a15d2d4d98a?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '256GB', ram: '8GB', color: 'Mint', screen: '6.7"' },
    description: 'Pocket-sized perfection. Flex Window lets you do more without opening your phone.',
    rating: 4.7,
    reviews: 112,
  },
  {
    id: 's23-fe',
    name: 'Samsung Galaxy S23 FE',
    brand: 'Samsung',
    category: 'Smartphone',
    price: 49999,
    originalPrice: 59999,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1610792516307-ea5acd9c3b00?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '128GB', ram: '8GB', color: 'Cream', screen: '6.4"' },
    description: 'Epic moments are now accessible to everyone. Pro-grade camera.',
    rating: 4.3,
    reviews: 56,
  },

  // --- GOOGLE PIXEL ---
  {
    id: 'pixel-7a',
    name: 'Google Pixel 7a',
    brand: 'Google',
    category: 'Smartphone',
    price: 37999,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff70?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '128GB', ram: '8GB', color: 'Sea', screen: '6.1"' },
    description: 'Built by Google. The smartest phone in its class.',
    rating: 4.5,
    reviews: 204,
  },
   {
    id: 'pixel-6-pro',
    name: 'Google Pixel 6 Pro',
    brand: 'Google',
    category: 'Smartphone',
    price: 28999,
    condition: 'Fair',
    image: 'https://images.unsplash.com/photo-1635870323382-748506079c65?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '128GB', ram: '12GB', color: 'Cloudy White', screen: '6.7"' },
    description: 'Still a camera beast. Excellent value for photography enthusiasts.',
    rating: 4.2,
    reviews: 310,
  },

  // --- ONEPLUS & OPPO ---
  {
    id: 'oneplus-11r',
    name: 'OnePlus 11R',
    brand: 'OnePlus',
    category: 'Smartphone',
    price: 35999,
    condition: 'Good',
    image: 'https://images.unsplash.com/photo-1662059374941-2c1b48b7921a?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '128GB', ram: '8GB', color: 'Sonic Black', screen: '6.7"' },
    description: 'Performance flagship. SuperVOOC charging keeps you going.',
    rating: 4.4,
    reviews: 95,
  },
  {
    id: 'oppo-reno-10',
    name: 'Oppo Reno 10 Pro',
    brand: 'Oppo',
    category: 'Smartphone',
    price: 39999,
    condition: 'Like New',
    image: 'https://images.unsplash.com/photo-1616348436168-de43ad0db179?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '256GB', ram: '12GB', color: 'Glossy Purple', screen: '6.7"' },
    description: 'The Portrait Expert. Telephoto lens for stunning bokeh.',
    rating: 4.3,
    reviews: 44,
  },

  // --- ACCESSORIES: AUDIO ---
  {
    id: 'airpods-pro-2',
    name: 'AirPods Pro (2nd Gen)',
    brand: 'Apple',
    category: 'Accessory',
    price: 24900,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1603351154351-5cfb3e988430?q=80&w=800&auto=format&fit=crop',
    specs: { color: 'White' },
    description: 'Rebuilt from the sound up. Up to 2x more Active Noise Cancellation.',
    rating: 4.9,
    reviews: 500,
    isTrending: true,
  },
  {
    id: 'airpods-max',
    name: 'AirPods Max',
    brand: 'Apple',
    category: 'Accessory',
    price: 59900,
    condition: 'Like New',
    image: 'https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?q=80&w=800&auto=format&fit=crop',
    specs: { color: 'Space Grey' },
    description: 'High-fidelity audio. The ultimate listening experience.',
    rating: 4.8,
    reviews: 120,
  },
  {
    id: 'galaxy-buds2-pro',
    name: 'Galaxy Buds2 Pro',
    brand: 'Samsung',
    category: 'Accessory',
    price: 12999,
    originalPrice: 17999,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1631281987622-79043236fb6a?q=80&w=800&auto=format&fit=crop',
    specs: { color: 'Bora Purple' },
    description: '24-bit Hi-Fi audio for a studio-quality listening experience.',
    rating: 4.6,
    reviews: 85,
  },
  {
    id: 'pixel-buds-pro',
    name: 'Google Pixel Buds Pro',
    brand: 'Google',
    category: 'Accessory',
    price: 13999,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1612444530582-fc66183b16f7?q=80&w=800&auto=format&fit=crop',
    specs: { color: 'Coral' },
    description: 'Silent Seal™ Active Noise Cancellation.',
    rating: 4.5,
    reviews: 67,
  },

  // --- ACCESSORIES: WATCHES ---
  {
    id: 'apple-watch-ultra-2',
    name: 'Apple Watch Ultra 2',
    brand: 'Apple',
    category: 'Accessory',
    price: 89900,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=800&auto=format&fit=crop',
    specs: { color: 'Titanium', screen: '49mm' },
    description: 'The most rugged and capable Apple Watch ever.',
    rating: 4.9,
    reviews: 150,
  },
  {
    id: 'galaxy-watch-6',
    name: 'Galaxy Watch 6 Classic',
    brand: 'Samsung',
    category: 'Accessory',
    price: 34999,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop',
    specs: { color: 'Black', screen: '47mm' },
    description: 'The rotating bezel is back. Advanced sleep coaching.',
    rating: 4.7,
    reviews: 90,
  },

  // --- ACCESSORIES: CHARGING & PROTECTION ---
  {
    id: 'magsafe-charger',
    name: 'MagSafe Charger',
    brand: 'Apple',
    category: 'Accessory',
    price: 4500,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1617042576045-849a6002f23b?q=80&w=800&auto=format&fit=crop',
    specs: { color: 'White' },
    description: 'Snap on charging. Faster wireless charging up to 15W.',
    rating: 4.8,
    reviews: 500,
  },
  {
    id: 'anker-powerbank',
    name: 'Anker 737 Power Bank',
    brand: 'OnePlus', 
    category: 'Accessory',
    price: 14999,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1609592425126-72cb6e93c6eb?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '24000mAh' },
    description: 'Ultra-powerful two-way charging. Charge your laptop and phone.',
    rating: 4.9,
    reviews: 120,
  },
  {
    id: 'leather-case-15',
    name: 'Nomad Leather Case',
    brand: 'Apple',
    category: 'Accessory',
    price: 5999,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1541140532154-b024d705b909?q=80&w=800&auto=format&fit=crop',
    specs: { color: 'Horween Brown' },
    description: 'Premium leather that develops a rugged patina.',
    rating: 4.7,
    reviews: 60,
  },
  
  // --- BUDGET & OLDER MODELS ---
  {
    id: 'iphone-11',
    name: 'iPhone 11',
    brand: 'Apple',
    category: 'Smartphone',
    price: 24999,
    condition: 'Fair',
    image: 'https://images.unsplash.com/photo-1574312330691-645396a56c07?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '64GB', ram: '4GB', color: 'Black', screen: '6.1"' },
    description: 'The perfect entry into the Apple ecosystem at an unbeatable price.',
    rating: 4.4,
    reviews: 1200,
  },
  {
    id: 'oneplus-nord-ce3',
    name: 'OnePlus Nord CE 3',
    brand: 'OnePlus',
    category: 'Smartphone',
    price: 24999,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1596742578443-7682ef5251cd?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '128GB', ram: '8GB', color: 'Aqua Surge', screen: '6.7"' },
    description: 'Everything you need, nothing you don\'t. Smooth experience.',
    rating: 4.3,
    reviews: 150,
  },
  {
    id: 'samsung-a54',
    name: 'Samsung Galaxy A54 5G',
    brand: 'Samsung',
    category: 'Smartphone',
    price: 35999,
    condition: 'Like New',
    image: 'https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '256GB', ram: '8GB', color: 'Awesome Violet', screen: '6.4"' },
    description: 'Premium glass finish, clean camera layout and energizing colors.',
    rating: 4.5,
    reviews: 89,
  },
  {
    id: 'pixel-6a',
    name: 'Google Pixel 6a',
    brand: 'Google',
    category: 'Smartphone',
    price: 22999,
    condition: 'Good',
    image: 'https://images.unsplash.com/photo-1667232386188-4447432f8086?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '128GB', ram: '6GB', color: 'Charcoal', screen: '6.1"' },
    description: 'Smart, powerful, helpful. And less than you think.',
    rating: 4.4,
    reviews: 412,
  },
  {
    id: 'oppo-find-n2',
    name: 'Oppo Find N2 Flip',
    brand: 'Oppo',
    category: 'Smartphone',
    price: 74999,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1681754028591-66795f62df3e?q=80&w=800&auto=format&fit=crop',
    specs: { storage: '256GB', ram: '8GB', color: 'Moonlit Purple', screen: '6.8"' },
    description: 'See more in a snap. The largest cover screen on a flip phone.',
    rating: 4.6,
    reviews: 32,
  },
  {
    id: 'sony-xm5',
    name: 'Sony WH-1000XM5',
    brand: 'Accessory' as any, // casting to avoid strict type error if type not updated, though we usually group by 'Accessory'
    category: 'Accessory',
    price: 26990,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=800&auto=format&fit=crop',
    specs: { color: 'Black' },
    description: 'Industry-leading noise cancellation. 30 hour battery life.',
    rating: 4.9,
    reviews: 450,
  }
];

export const CATEGORIES = [
  { id: 'new', title: 'The New Collection', description: 'Latest Mobiles & Accessories', image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=800&auto=format&fit=crop' },
  { id: 'pre-owned', title: 'Pre-Loved Excellence', description: 'Certified & Tested', image: 'https://images.unsplash.com/photo-1550029402-226115b7c579?q=80&w=800&auto=format&fit=crop' },
  { id: 'accessories', title: 'Essentials', description: 'Premium Accessories', image: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?q=80&w=800&auto=format&fit=crop' },
];

export const BRANDS = ['Apple', 'Samsung', 'Google', 'OnePlus', 'Oppo'];
export const CONDITIONS = ['New', 'Like New', 'Good', 'Fair'];
